version: '0.2'
language: en,de-DE,it,es-ES
ignorePaths:
  - '**/node_modules/**'
  - '**/vscode_extension/**'
  - '**/.git/**'
  - '**/.pnpm-lock.json'
  - '**/pnpm-lock.yaml'
  - '**/yarn.lock'
  - dist/
  - out/
  - build/
  - .vscode
  - package-lock.json
  - megalinter-reports
  - .devcontainer/.dockerignore
  - .gitattributes
  - .gitignore
  - .prettierignore
  - CHANGELOG.md
  - LICENSE
  - LICENSES/**
  - cspell.config.yaml
files:
  - '*/**'
words:
  - jmuelbert
  - Jürgen
  - Mülbert
flagWords:
  - hte->the
maxNumberOfProblems: 1000
import: []
useGitignore: true
overrides:
  - filename: '**/de_DE/**'
    language: en,de
  - filename: '**/nl_NL/**'
    language: en,nl
  - filename: '**/ru_RU/samples/**'
    language: ru,en
  - filename: '**/sv/**'
    language: en,sv
  - filename: package.json
    ignoreWords:
      - colour
      - canot
allowCompoundWords: true
enableGlobDot: true
cache:
  useCache: true
  cacheStrategy: content
enableFiletypes:
  - shellscript
dictionaryDefinitions:
  - name: ./project-words
    addWords: true
    scope:
      - workspace
    path: ./project-words.txt
dictionaries:
  - ./project-words
  - bash
  - companies
  - csharp
  - css
  - filetypes
  - fonts
  - misc
  - node
  - npm
  - powershell
  - python
  - software-terms
  - typescript
